- name: syncthing container
  docker_container:
    name: syncthing
    image: lscr.io/linuxserver/syncthing:latest
    restart_policy: unless-stopped
    network_mode: host
    env:
      TZ: America/New_York
      PUID: '1000'
      PGID: '1000'
    volumes:
      - '{{ syncthing_config_dir }}/config'
      - '{{ syncthing_data_dir }}:/data'
